"""create vehicles table

Revision ID: 26e2eb117333
Revises: 
Create Date: 2025-09-11 10:18:48.943458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e2eb117333'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('doors', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('engineSize', sa.Float(), nullable=True))
    op.create_index(op.f('ix_vehicles_doors'), 'vehicles', ['doors'], unique=False)
    op.create_index(op.f('ix_vehicles_engineSize'), 'vehicles', ['engineSize'], unique=False)
    op.create_index(op.f('ix_vehicles_year'), 'vehicles', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_year'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_engineSize'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_doors'), table_name='vehicles')
    op.drop_column('vehicles', 'engineSize')
    op.drop_column('vehicles', 'doors')
    op.drop_column('vehicles', 'year')
    # ### end Alembic commands ###
